logs

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -71,10 +71,12 @@ runs:
           fi
         }
         get_token() {
+          echo "get_token" 1>&2
           if [[ $(available_and_exists "$1") == 'true' ]]; then
             prepare=$(curl -s -X POST --cookie "session=$SESSION_TOKEN" -H "Referer: https://armconverter.com/decryptedappstore" "https://armconverter.com/decryptedappstore/download/$appstore_id/$bundle_id/$(echo $1 | jq -r .ver)/prepare")
             error=$(echo $prepare | jq -r .error)
             token=$(echo $prepare | jq -r .token)
+            echo "$error" 1>&2
             if [[ ! -z $error && $error != 'null' ]]; then
               echo "$error" 1>&2
               echo 'null'
